// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function clientFor(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista leads capturados no site, com filtros opcionais por status, cidade e limite.",
  inputSchema: {
    status: z.enum(["novo", "em_contato", "ganho", "perdido"]).optional().describe("Filtra por status do lead."),
    city: z.string().optional().describe("Filtra por cidade (correspond\xEAncia parcial)."),
    limit: z.number().int().min(1).max(200).optional().describe("N\xFAmero m\xE1ximo de leads a retornar (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, city, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = clientFor(ctx);
    let q = supabase.from("leads").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (city) q = q.ilike("city", `%${city}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function clientFor2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Detalhar lead",
  description: "Retorna os dados completos de um lead pelo id, incluindo follow-ups registrados.",
  inputSchema: { id: z2.string().uuid().describe("UUID do lead.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = clientFor2(ctx);
    const [lead, followups] = await Promise.all([
      supabase.from("leads").select("*").eq("id", id).maybeSingle(),
      supabase.from("lead_followups").select("*").eq("lead_id", id).order("created_at", { ascending: false })
    ]);
    if (lead.error) return { content: [{ type: "text", text: lead.error.message }], isError: true };
    if (!lead.data) return { content: [{ type: "text", text: "Lead n\xE3o encontrado." }], isError: true };
    const payload = { lead: lead.data, followups: followups.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/update-lead-status.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function clientFor3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_lead_status_default = defineTool3({
  name: "update_lead_status",
  title: "Atualizar status do lead",
  description: "Muda o status de um lead (novo, em_contato, ganho, perdido). Dispara automaticamente o follow-up configurado.",
  inputSchema: {
    id: z3.string().uuid().describe("UUID do lead."),
    status: z3.enum(["novo", "em_contato", "ganho", "perdido"]).describe("Novo status do lead.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const { data, error } = await clientFor3(ctx).from("leads").update({ status }).eq("id", id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Status atualizado para ${status}.` }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/add-lead-note.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function clientFor4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_lead_note_default = defineTool4({
  name: "add_lead_note",
  title: "Adicionar nota ao lead",
  description: "Anexa uma anota\xE7\xE3o ao campo de notas do lead (concatena com as anota\xE7\xF5es existentes).",
  inputSchema: {
    id: z4.string().uuid().describe("UUID do lead."),
    note: z4.string().min(1).describe("Texto da nota a adicionar.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ id, note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = clientFor4(ctx);
    const { data: current, error: readErr } = await supabase.from("leads").select("notes").eq("id", id).maybeSingle();
    if (readErr) return { content: [{ type: "text", text: readErr.message }], isError: true };
    if (!current) return { content: [{ type: "text", text: "Lead n\xE3o encontrado." }], isError: true };
    const stamp = (/* @__PURE__ */ new Date()).toISOString();
    const nextNotes = [current.notes, `[${stamp}] ${note}`].filter(Boolean).join("\n");
    const { error } = await supabase.from("leads").update({ notes: nextNotes }).eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: "Nota adicionada." }] };
  }
});

// src/lib/mcp/tools/leads-stats.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
function clientFor5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var leads_stats_default = defineTool5({
  name: "leads_stats",
  title: "Estat\xEDsticas de leads",
  description: "Resumo agregado dos leads: total, contagem por status e score m\xE9dio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const { data, error } = await clientFor5(ctx).from("leads").select("status, base_score");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const byStatus = {};
    let sum = 0;
    for (const r of rows) {
      byStatus[r.status] = (byStatus[r.status] ?? 0) + 1;
      sum += Number(r.base_score) || 0;
    }
    const stats = {
      total: rows.length,
      by_status: byStatus,
      average_score: rows.length ? Math.round(sum / rows.length * 10) / 10 : 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uqzmhwzhkurcyyziujwe";
var mcp_default = defineMcp({
  name: "seu-dinheiro-recuperado-mcp",
  title: "Seu Dinheiro Recuperado \u2014 Painel de Leads",
  version: "0.1.0",
  instructions: "Ferramentas para consultar e gerenciar leads do site Seu Dinheiro Recuperado. Use `list_leads` para buscar, `get_lead` para detalhes, `update_lead_status` para mover no funil, `add_lead_note` para anota\xE7\xF5es e `leads_stats` para m\xE9tricas agregadas.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, update_lead_status_default, add_lead_note_default, leads_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
